# Generated by Django 3.0.7 on 2020-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200723_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
